# Generated by Django 5.2.4 on 2025-12-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do cliente"),
                ),
                (
                    "dominio",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="domínio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo?")),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nome"],
            },
        ),
    ]
